### ISSUE TITLE
Peak cpu and peak memory are wrong

### ISSUE THREAD

**Issue by R-daneel-olivaw** [R-daneel-olivaw/CPET#2]
Module 2 is showing wrong figures for peak cpu and peak memory statistics.

**Comment by manishchauhan184** [comment]
It's a small code, debugging should not be a problem. We can work on it tomorrow. Regards,
Manish Chauhan

**Comment by R-daneel-olivaw** [comment]
Hi @manishchauhan184 , the issue has already been fixed :+1: 
The fix can be found here 6c57a7d13596a62d278042b143e120714161cd30
